In [21]:
import pickle
import map_utils
import torchvision.transforms as transforms
import torch

with open('test_func.pkl', 'rb') as file:

    data = pickle.load(file)

gt_lines_instance = data['gt_vecs_pts_loc'].instance_list

gt_lines_instance

In [37]:
intrinsic = data['camera_intrinsics']

In [40]:
extrinsic = data["camera2ego"]
extrinsic

tensor([[ 0.8225,  0.0065,  0.5687,  1.5753],
        [-0.5687,  0.0164,  0.8224,  0.5005],
        [-0.0040, -0.9998,  0.0172,  1.5070],
        [ 0.0000,  0.0000,  0.0000,  1.0000]])

In [41]:
extrinsic[:3, 3].reshape(3, -1)

tensor([[1.5753],
        [0.5005],
        [1.5070]])

In [33]:
data

{'gt_vecs_pts_loc': <map_utils.LiDARInstanceLines at 0x7f7dbd351730>,
 'gt_vecs_label': tensor([0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2]),
 'camera_intrinsics': tensor([[1.2726e+03, 0.0000e+00, 8.2662e+02, 0.0000e+00],
         [0.0000e+00, 1.2726e+03, 4.7975e+02, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00]]),
 'camera2ego': tensor([[ 0.8225,  0.0065,  0.5687,  1.5753],
         [-0.5687,  0.0164,  0.8224,  0.5005],
         [-0.0040, -0.9998,  0.0172,  1.5070],
         [ 0.0000,  0.0000,  0.0000,  1.0000]])}

In [26]:
list(gt_lines_instance[0].coords)

[(6.216248787878953, -9.059982842706233),
 (6.678621338833864, -8.967911239365378),
 (7.140993889788888, -8.87583963602458),
 (7.603366440743798, -8.783768032683781),
 (8.065738991698709, -8.691696429342926),
 (8.528111542653733, -8.599624826002128),
 (8.990484093608643, -8.507553222661272),
 (9.452856644563553, -8.415481619320644),
 (9.91522919551835, -8.323410015979789),
 (10.377601746473488, -8.231338412638934),
 (10.839974297428398, -8.139266809298078),
 (11.302346848383195, -8.047195205957337),
 (11.764719399338219, -7.955123602616538),
 (12.227091950293243, -7.86305199927574),
 (12.68946450124804, -7.770980395934885),
 (13.151837052203064, -7.678908792594086),
 (13.614209603157974, -7.586837189253345),
 (14.076582154112884, -7.494765585912489),
 (14.538954705067908, -7.402693982571691),
 (15.001327256022705, -7.310622379230836),
 (15.463699806977843, -7.21855077588998),
 (15.926072357932753, -7.126479172549239),
 (16.38844490888755, -7.034407569208497),
 (16.850817459842688, -6.9

In [31]:
gt_labels_3d = data["gt_vecs_label"]
z = 0

In [48]:
for gt_line_instance, gt_label_3d in zip(gt_lines_instance, gt_labels_3d):
        pts = torch.Tensor(list(gt_line_instance.coords))
        # print(pts)
        pts = pts[:, [1, 0]]
        pts[:, 1] = -pts[:, 1]
        dummy_pts = torch.cat([pts, torch.ones((pts.shape[0], 1)) * z], dim=-1)
        points_in_cam_cor = torch.matmul(
            extrinsic[:3, :3].T, (dummy_pts.T - extrinsic[:3, 3].reshape(3, -1))
        )
        print(points_in_cam_cor)


torch.Size([50, 3])
tensor([[ 0.8225, -0.5687, -0.0040],
        [ 0.0065,  0.0164, -0.9998],
        [ 0.5687,  0.8224,  0.0172]])
torch.Size([14, 3])
tensor([[ 0.8225, -0.5687, -0.0040],
        [ 0.0065,  0.0164, -0.9998],
        [ 0.5687,  0.8224,  0.0172]])
torch.Size([5, 3])
tensor([[ 0.8225, -0.5687, -0.0040],
        [ 0.0065,  0.0164, -0.9998],
        [ 0.5687,  0.8224,  0.0172]])
torch.Size([38, 3])
tensor([[ 0.8225, -0.5687, -0.0040],
        [ 0.0065,  0.0164, -0.9998],
        [ 0.5687,  0.8224,  0.0172]])
torch.Size([50, 3])
tensor([[ 0.8225, -0.5687, -0.0040],
        [ 0.0065,  0.0164, -0.9998],
        [ 0.5687,  0.8224,  0.0172]])
torch.Size([32, 3])
tensor([[ 0.8225, -0.5687, -0.0040],
        [ 0.0065,  0.0164, -0.9998],
        [ 0.5687,  0.8224,  0.0172]])
torch.Size([8, 3])
tensor([[ 0.8225, -0.5687, -0.0040],
        [ 0.0065,  0.0164, -0.9998],
        [ 0.5687,  0.8224,  0.0172]])
torch.Size([3, 3])
tensor([[ 0.8225, -0.5687, -0.0040],
        [ 0.0065,  0.0